llscircle: main.cpp imgutil.h util.h gfxutil.h
	g++ -g -o llscircle main.cpp -lpng -lglut

clean:
	rm llscircle

run:
	./llscircle circle-10.png
#	./llscircle circle-single-basic.png

debug:
	gdb ./llscircle
