#mandle_single: mandel_single.c
#	gcc mandel_single.c /usr/lib/libpng.a /usr/lib/libz.so -o mandel_single

mandle_static: mandel_static.c
	gcc mandel_static.c /usr/lib/libpng.a /usr/lib/libz.so -o mandel_static



