generator: generator.cpp
	g++ -o generator generator.cpp

bubblesort: bubblesort.cpp
	g++ -o bubblesort bubblesort.cpp

countingsort: countingsort.cpp
	g++ -o countingsort countingsort.cpp

quicksort: quicksort.cpp
	g++ -o quicksort quicksort.cpp

oursort: oursort.cpp
	g++ -o oursort oursort.cpp

insertionsort: insertionsort.cpp
	g++ -o insertionsort insertionsort.cpp

mergesort: mergesort.cpp
	g++ -o mergesort mergesort.cpp

heapsort: heapsort.cpp
	g++ -o heapsort heapsort.cpp

woonsort: woonsort.cpp
	g++ -o woonsort woonsort.cpp

cleanup:
	rm generator bubblesort countingsort quicksort oursort insertionsort
